version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    environment:
      BACKEND1_URL: http://backend1:5000/rolldice
      BACKEND2_URL: http://backend2:5165/rolldice
  backend1:
    build: ./backend-python
    ports:
      - "5000:5000"
  backend2:
    build: ./backend-java
    ports:
      - "5165:5165"
  loadgen:
    build: ./loadgen
    scale: 2
    depends_on:
      - frontend
      - backend1
      - backend2
